### PR TITLE
Fix build errors on Mac Yosemite

### PR DESCRIPTION
**Pull request by maojie**
1. error: no template named 'scoped_ptr' in namespace 'boost'; did you
mean 'boost::asio::detail::scoped_ptr'
2. /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/utility:294:15:
error: read-only variable is not assignable

### CODE REVIEW

**Comment by pawanvivekananda** [comment]
Thank you for the fix and raising the PULL request. 
I was also facing the same issue, I figured that out, but now i am struck ErizoApi Error

"no type named 'Arguments' in namespace 'v8'; did you mean 'v8::internal::Arguments'?
        static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments"

The work around that i found is to down grade the nodejs from 0.12.0 to 0.10.0 

If u have any better way without down grade the nodejs? If so can u please share your thoughts ..

**Comment by maojie** [comment]
I've simply checked the changes in nodejs from v0.12.* to v.10.*, it seems that the definition of v8::Arguments is been removed in v0.12.*, so it'll generate the above errors. I'm not sure if licode works well on Ubuntu with nodejs v0.12.0, but I'll try to find a way to fix that.

**Comment by mrbatista** [comment]
What is your setup? (OS version, dependencies of licode with version)
I Try to install licode with [this] (https://github.com/ging/licode/blob/master/scripts/installMacDeps.sh) script, but i have problem when compile ErizoAPI.
Thanks for your sharing.

**Comment by maojie** [comment]
OS version: OSX Yosemite, Nodejs version: v0.10.6, I think the reason you can't compile ErizoAPI is due to the Nodejs's version, you may switch Nodejs version to v0.10.6 to have a try.

**Comment by lodoyun** [comment]
Looks good,
Thanks!

**Pull request merged**
