### PR TITLE
Moved the mapping of rtcp-fb lines till after we build a rtpmap vector

### PR DESCRIPTION
**Pull request by sherwinsim**
Fixes: Although the original issue was worked around with commit c07f1d46177d0e642a51e21ca761454259997d72, that commit fixes the issue at the client side and not the server side. This fix will allow Erizo to properly parse SDPs natively from Firefox 37 and up

Use Case: We use Licode server as our backend but we do not use the Licode client side.

### CODE REVIEW

**Comment by zevarito** [comment]
@sherwinsim Can I ask how is to use Licode just in the backend? What are you using for Client side?

**Comment by sherwinsim** [comment]
Sure, Licode drives some of the MCU based features in the Skylink.io platform. We develop a variety of client side SDKs for platform developers to use.

**Comment by zevarito** [comment]
@sherwinsim that's cool!

**Comment by lodoyun** [comment]
Thanks!
Sorry it took so long

**Comment by sherwinsim** [comment]
No worries, I figure a fix on the server side would help things

**Pull request merged**
