### PR TITLE
[FEATURE-REVIEW] Single Peer Connections

### PR DESCRIPTION
**Pull request by jcague**
In this PR I want to propose to change our current approach to support Single Peer Connections.

Main advantage: reduce usage of UDP ports and time to subscribe to new streams.

Please, provide as much feedback as possible to this proposal!!

### CODE REVIEW

**Comment by notedit** [comment]
the two message flow  is the same.  maybe you refer the wrong image

**Comment by jcague** [comment]
good catch @notedit ! I've fixed it already.

**Comment by zevarito** [comment]
@jcague will this change leave Multiple Peer Connections still working and add Single Peer Connection as an option? Also, wasn't clear to me after reading your diagrams if it will provide backward compatibility or not? Thanks and good work!

**Comment by jcague** [comment]
@zevarito yep, that's something that we should tackle in the document. Thanks for the heads up!

**Comment by jcague** [comment]
@aalonsog @lodoyun @notedit @zevarito I updated this document with further logic / architecture / comments, can you review it again and provide feedback, please?

**Comment by lodoyun** [comment]
In general I do like the direction you are proposing for this.
A couple of thoughts:

- ErizoClient should be in charge of absorbing the implementation differences in the browsers. We could gradually enable single PeerConnection in different browsers as we implement it. 

- We should define in this stage a working policy for ErizoController. For instance, by default, the policy should try to keep rooms within the same ErizoJS whenever possible and evenly distribute the rooms evenly among the available ErizoJs processes. I know there are a million ways to optimize this but it's a start.

**Comment by jcague** [comment]
@lodoyun good catch! I just added a simple policy that could help us as a starting point and commented your first point in the document.

**Comment by jcague** [comment]
I'd like to finish this review on Monday if I don't receive more feedback/requests. We will be able to change it in the future whenever we find issues, 

@jnoring any thoughts or feedback on this feature?

**Comment by notedit** [comment]
hi  @jcague    that means   we can use  multi  streams over on peerconnection  in  client side?

**Comment by notedit** [comment]
i see the  this planB  https://tools.ietf.org/html/draft-ietf-rtcweb-rtp-usage-26

**Comment by notedit** [comment]
it seems that  webrtc will support  Unified Plan.

https://bugs.chromium.org/p/chromium/issues/detail?id=465349

**Pull request merged**
