### PR TITLE
Fix External Input and External Output destruction

### PR DESCRIPTION
**Pull request by jcague**

### CODE REVIEW

**Comment by jcague** [comment]
@kekkokk this should fix your problem when stopping recordings.

**Comment by kekkokk** [comment]
@jcague unfortunately no, after the first stop (which is slightly delayed too), there is still a considerable delay.

**Comment by kekkokk** [comment]
I confirm, tried with a fresh install. same issue

**Comment by jcague** [comment]
@kekkokk I did more changes and tested them successfully in my machine, can you try it again please?

**Comment by kekkokk** [comment]
works like a charm, thank you!

**Pull request merged**
