### PR TITLE
Do not use deprecated Firefox media functions

### PR DESCRIPTION
**Pull request by cracker0dks**
Change to current media functions
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia

### CODE REVIEW

**Comment by jnoring** [comment]
This isn't backwards compatible with old versions of firefox.  What Licode really needs to do is start using adapter.js instead of providing its own shims for getUserMedia().

**Comment by cracker0dks** [comment]
yeah maybe you are right. But who i using webRTC with an old browser ? adapter.js would be nice.

**Comment by zevarito** [comment]
+1 to use AdapterJs.

2016-04-18 13:15 GMT-03:00 Cracker <notifications@github.com>:

> yeah maybe you are right. But who i using webRTC with an old browser ?
> adapter.js would be nice.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ging/licode/pull/437#issuecomment-211451354>
>



-- 
Alvaro

**Comment by jnoring** [comment]
I have lots of users who unfortunately use WebRTC with old browsers. :(

**Comment by enricop89** [comment]
Why did you close it? It seems to work well

**Comment by cracker0dks** [comment]
because you are not backwards compatible and so this will probably not get merged. It is also better to implement adapter.js than merge this :)

**Comment by enricop89** [comment]
It sound reasonable. Have you already tried to implement adapter.js?

**Comment by cracker0dks** [comment]
no not yet.  If I get problems with the current solution maybe I will. 

PS: You also dont know if they will merge this because there are many other updates like node, socket.io or ssl witch dont get merged (for most undefined reasons). So if you change your code to adapter.js you will probably get trouble every time you pull an update from this code base. #NotWorthATM

**Pull request closed without merging**
